[package]
name = "aris"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytes = "1.9.0"
crossbeam = { version = "0.8.4", features = ["crossbeam-epoch"] }
mimalloc = "0.1.43"
rand = "0.8.5"
thiserror = "2.0.11"
