[package]
name = "arisdb"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.0"
crc32fast = "1.4.2"
ctor = "0.2.9"
mimalloc = "0.1.43"
rand = "0.9.0"
rio = "0.9.4"
thiserror = "2.0.11"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
